app/urls.py
from django.urls import path
from .views import HomeView, ItemDetailView, add_to_cart, remove_from_cart, OrderSummaryView,remove_single_item_from_cart,CheckoutView, PaymentView

app_name = "app"

urlpatterns = [

 path('',HomeView.as_view(), name="home"),
 path('product/<slug>/',ItemDetailView.as_view(), name="product"),
 path('order-summary/',OrderSummaryView.as_view(), name="order-summary"),
 path('checkout/',CheckoutView.as_view(), name="checkout"),
 path('add_to_cart/<slug>/', add_to_cart, name="add_to_cart"),
 path('remove_from_cart/<slug>/', remove_from_cart, name="remove_from_cart"),
 path('remove_item_from_cart/<slug>/', remove_single_item_from_cart, name="remove_item_from_cart"),
 path('payment/<payment_option>/', PaymentView.as_view(), name='payment')

]

commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('app.urls'))

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField


# Create your models here.

CATEGORY_CHOICES = (
	('S','Shirt'),
	('SW','Sport Wear'),
	('OW','Out Wear')
)

LABEL_CHOICES = (
	('P','primary'),
	('S','secondary'),
	('D','danger')
)

class Item(models.Model):
	title = models.CharField(max_length=100)
	price = models.FloatField()
	discount_price = models.FloatField(blank=True, null=True)
	category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
	label = models.CharField(choices=LABEL_CHOICES, max_length=1)
	slug = models.SlugField()
	description = models.TextField()

	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse("app:product", kwargs={
			'slug': self.slug
		})
	def get_add_to_cart_url(self):
		return reverse("app:add_to_cart", kwargs={
			'slug': self.slug
		})
	
	def get_remove_from_cart_url(self):
		return reverse("app:remove_from_cart", kwargs={
			'slug': self.slug
		})



class OrderItem(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	ordered = models.BooleanField(default=False)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)




	def __str__(self):
		return f"{self.quantity} of {self.item.title}"

	def get_total_item_price(self):
		return self.quantity * self.item.price

	def get_total_discount_item_price(self):
		return self.quantity * self.item.discount_price

	def get_amount_saved(self):
		return self.get_total_item_price() - self.get_total_discount_item_price()

	def get_final_price(self):
		if self.item.discount_price:
			return self.get_total_discount_item_price()
		return self.get_total_item_price()

class Order(models.Model):

	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	item = models.ManyToManyField(OrderItem)
	start_date = models.DateTimeField(auto_now_add = True)
	ordered_date = models.DateTimeField()
	ordered = models.BooleanField(default=False)
	billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)

	def __str__(self):
		return self.user.username

	def get_total(self):
		total = 0
		for order_item in self.item.all():
			total += order_item.get_final_price()
		return total

class BillingAddress(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	street_address = models.CharField(max_length=100)
	apartment_address = models.CharField(max_length=100)
	country = CountryField(multiple=False)
	zips = models.CharField(max_length=100)

	def __str__(self):
		return self.user.username

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
     <title>
      {% block head_title %}
      {% endblock %}
      </title>
      {% block extra_head %}
      {% endblock %}
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"
    />
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet" />
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet" />
    <style type="text/css">
      html,
      body,
      header,
      .carousel {
        height: 60vh;
      }

      @media (max-width: 740px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }

      @media (min-width: 800px) and (max-width: 850px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }
    </style>
  </head>

  <body>
    {% include 'navbar.html' %}

    <div class="mt-5 pt-4">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %} {% endif %}
    </div>

   
    <!--Main layout-->
    <main>
      <div class="container">
         {% include 'pagination.html'%}
         {% block content %} 
         {% endblock %}

          {% block extra_body %}
          {% endblock %}




        <!--Pagination-->
        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            <!--Arrow left-->
              {% if page_obj.has_previous %}
            <li class="page-item ">
              <a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
              {% endif %}
            <li class="page-item active">
              <a class="page-link" href="?page={{page_obj.number}}">1
                <span class="sr-only">(current)</span>
              </a>
            </li>
        
             {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}
        <!--Pagination-->
      </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
     

      <hr class="my-4" />

      <!-- Social icons -->
      <div class="pb-4">
        <a href="https://www.facebook.com/mdbootstrap" target="_blank">
          <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <a href="https://twitter.com/MDBootstrap" target="_blank">
          <i class="fab fa-twitter mr-3"></i>
        </a>

        <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
          <i class="fab fa-youtube mr-3"></i>
        </a>

        <a
          href="https://plus.google.com/u/0/b/107863090883699620484"
          target="_blank"
        >
          <i class="fab fa-google-plus-g mr-3"></i>
        </a>

        <a href="https://dribbble.com/mdbootstrap" target="_blank">
          <i class="fab fa-dribbble mr-3"></i>
        </a>

        <a href="https://pinterest.com/mdbootstrap" target="_blank">
          <i class="fab fa-pinterest mr-3"></i>
        </a>

        <a
          href="https://github.com/mdbootstrap/bootstrap-material-design"
          target="_blank"
        >
          <i class="fab fa-github mr-3"></i>
        </a>

        <a href="http://codepen.io/mdbootstrap/" target="_blank">
          <i class="fab fa-codepen mr-3"></i>
        </a>
      </div>
      <!-- Social icons -->

      <!--Copyright-->
      <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank">
          MDBootstrap.com
        </a>
      </div>
      <!--/.Copyright-->
    </footer>
    <!--/.Footer-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script
      type="text/javascript"
      src="{% static 'js/jquery-3.4.1.min.js' %}"
    ></script>
    <!-- Bootstrap tooltips -->
    <script
      type="text/javascript"
      src="{% static 'js/popper.min.js' %}"
    ></script>
    <!-- Bootstrap core JavaScript -->
    <script
      type="text/javascript"
      src="{% static 'js/bootstrap.min.js' %}"
    ></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
      // Animations initialization
      new WOW().init();
    </script>
  </body>
</html>

templates/carousel.html
<!--Carousel Wrapper-->
<div
  id="carousel-example-1z"
  class="carousel slide carousel-fade pt-4"
  data-ride="carousel"
>
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li
      data-target="#carousel-example-1z"
      data-slide-to="0"
      class="active"
    ></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="
            mask
            rgba-black-strong
            d-flex
            justify-content-center
            align-items-center
          "
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Learn Bootstrap 4 with MDB</strong>
            </h1>

            <p>
              <strong>Best & free guide of responsive web design</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              target="_blank"
              href="https://mdbootstrap.com/education/bootstrap/"
              class="btn btn-outline-white btn-lg"
              >Start free tutorial
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="
            mask
            rgba-black-strong
            d-flex
            justify-content-center
            align-items-center
          "
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Learn Bootstrap 4 with MDB</strong>
            </h1>

            <p>
              <strong>Best & free guide of responsive web design</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              target="_blank"
              href="https://mdbootstrap.com/education/bootstrap/"
              class="btn btn-outline-white btn-lg"
              >Start free tutorial
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Second slide-->

    <!--Third slide-->
    <div class="carousel-item">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="
            mask
            rgba-black-strong
            d-flex
            justify-content-center
            align-items-center
          "
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Learn Bootstrap 4 with MDB</strong>
            </h1>

            <p>
              <strong>Best & free guide of responsive web design</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              target="_blank"
              href="https://mdbootstrap.com/education/bootstrap/"
              class="btn btn-outline-white btn-lg"
              >Start free tutorial
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a
    class="carousel-control-prev"
    href="#carousel-example-1z"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#carousel-example-1z"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->

templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">
  <!--Call to action-->
  <div class="pt-4">
    <a
      class="btn btn-outline-white"
      href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
      target="_blank"
      role="button"
      >Download MDB
      <i class="fas fa-download ml-2"></i>
    </a>
    <a
      class="btn btn-outline-white"
      href="https://mdbootstrap.com/education/bootstrap/"
      target="_blank"
      role="button"
      >Start free tutorial
      <i class="fas fa-graduation-cap ml-2"></i>
    </a>
  </div>
  <!--/.Call to action-->

  <hr class="my-4" />

  <!-- Social icons -->
  <div class="pb-4">
    <a href="https://www.facebook.com/mdbootstrap" target="_blank">
      <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="https://twitter.com/MDBootstrap" target="_blank">
      <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a
      href="https://plus.google.com/u/0/b/107863090883699620484"
      target="_blank"
    >
      <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="https://dribbble.com/mdbootstrap" target="_blank">
      <i class="fab fa-dribbble mr-3"></i>
    </a>

    <a href="https://pinterest.com/mdbootstrap" target="_blank">
      <i class="fab fa-pinterest mr-3"></i>
    </a>

    <a
      href="https://github.com/mdbootstrap/bootstrap-material-design"
      target="_blank"
    >
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="http://codepen.io/mdbootstrap/" target="_blank">
      <i class="fab fa-codepen mr-3"></i>
    </a>
  </div>
  <!-- Social icons -->

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank">
      MDBootstrap.com
    </a>
  </div>
  <!--/.Copyright-->
</footer>
<!--/.Footer-->

templates/home.html
{% extends 'base.html' %} 
{% block content %}

 <main>
      <div class="container">
        
<!--Section: Products v.3-->
<section class="text-center mb-4">
  <!--Grid row-->

  <div class="row wow fadeIn">
    {% for item in object_list %}
    <!--Grid column-->
    <div class="col-lg-3 col-md-6 mb-4">
      <!--Card-->
      <div class="card">
        <!--Card image-->
        <div class="view overlay">
          <img
            src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
            class="card-img-top"
            alt=""
          />
          <a href="{{item.get_absolute_url}}">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>
        <!--Card image-->

        <!--Card content-->
        <div class="card-body text-center">
          <!--Category & Title-->
          <a href="" class="grey-text">
            <h5>{{ item.get_category_display }}</h5>
          </a>
          <h5>
            <strong>
              <a href="{{item.get_absolute_url}}" class="dark-grey-text"
                >{{item.title}}
                <span
                  class="badge badge-pill {{ item.get_label_display }}-color"
                  >NEW</span
                >
              </a>
            </strong>
          </h5>

          <h4 class="font-weight-bold blue-text">
            <strong>
              {% if item.discount_price %} {{item.discount_price}} {% else %}
              {{item.price}} {% endif %}
            </strong>
          </h4>
        </div>
        <!--Card content-->
      </div>
      <!--Card-->
    </div>
    {% endfor %}
    <!--Grid column-->
  </div>

  <!--Grid row-->
</section>
<!--Section: Products v.3-->

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}
<!-- Navbar -->
<nav
  class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar"
>
  <div class="container">
    <!-- Brand -->
    <a class="navbar-brand waves-effect"
      href="/">
      <strong class="blue-text">WRCommerce</strong>
    </a>

    <!-- Collapse -->
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left -->
      <ul class="navbar-nav mr-auto">
       <!--  <li class="nav-item active">
          <a class="nav-link waves-effect" href="/"
            >Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'app:checkout' %}"
            >Checkout</a
          >
        </li> -->
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'app:order-summary'%}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count}} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
          </a>
        </li>
        {% else %}
         <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Login </span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->

templates/order_summary.html
{% extends 'base.html' %} 
{% block content %}

 <main>
        <div class="container">
          <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Item</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total</th>
                  </tr>
                </thead>
                <tbody>
                  {% for order_item in object.item.all %}
                  <tr>
                    <th scope="row">{{ forloop.counter}}</th>
                    <td>{{order_item.item.title}}</td>
                    <td>{{order_item.item.price}}</td>
                    <td><a href="{% url 'app:remove_item_from_cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>{{order_item.quantity}}<a href="{% url 'app:add_to_cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a></td>
                    <td>
                      
                      {% if order_item.item.discount_price %}
                       &#8358; {{order_item.get_total_discount_item_price}}
                       <span class="badge badge-primary">saving  &#8358;{{order_item.get_amount_saved}}</span>
                      {% else %}
                       &#8358; {{order_item.get_total_item_price}}
                      {% endif %}
                      <a style="color: red" href="{% url 'app:remove_from_cart' order_item.item.slug %}"><i class="fas fa-trash float-right"></i></a>
                    </td>
                  </tr>

                  {% empty %}

                  <tr>
                    <td colspan="5">Your cart is empty</td>
                  </tr>
                    <tr>
                    <td colspan="5">
                      <a class="btn btn-primary float-right" href="/">Continue shopping</a>
                    </td>
                  </tr>

                  
                  {% endfor %}

                  {% if object.get_total %}

                  <tr>
                    <td colspan="4"><b>Order Total</b></td>
                    <td> <b>&#8358;{{object.get_total}}</b></td>
                  </tr>

                  <tr>
                    <td colspan="5">
                      <a class="btn btn-warning float-right ml-2" href="/checkout/">Proceed to checkout</a>
                      <a class="btn btn-primary float-right" href="/">Continue shopping</a>
                    </td>
                  </tr>
                  {% endif %}
                </tbody>
              </table>
            </div>
        </div>
  </main>

{% endblock content %}

templates/pagination.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">
  <!-- Navbar brand -->
  <span class="navbar-brand">Categories:</span>

  <!-- Collapse button -->
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#basicExampleNav"
    aria-controls="basicExampleNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">
    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"
          >All
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Shirts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Sport wears</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Outwears</a>
      </li>
    </ul>
    <!-- Links -->

    <form class="form-inline">
      <div class="md-form my-0">
        <input
          class="form-control mr-sm-2"
          type="text"
          placeholder="Search"
          aria-label="Search"
        />
      </div>
    </form>
  </div>
  <!-- Collapsible content -->
</nav>
<!--/.Navbar-->

templates/product.html
{% extends 'base.html' %} {% block content %}
<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">
    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <!--Content-->
        <div class="p-4">
          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1"
                >{{ object.get_category_display }}</span
              >
            </a>
          </div>

          <p class="lead">
            {% if object.discount_price %}
            <span class="mr-1">
              <del>{{ object.price }}</del>
            </span>
            <span>{{ object.discount_price }}</span>
            {% else %}
            <span>{{object.price}}</span>
            {% endif %}
          </p>

          <p class="lead font-weight-bold">Description</p>

          <p>{{ object.description}}</p>

          <a
            href="{{ object.get_add_to_cart_url}}"
            class="btn btn-primary btn-md my-0 p"
          >
            Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>

          <a
            href="{{ object.get_remove_from_cart_url}}"
            class="btn btn-danger btn-md my-0 p"
          >
            remove from cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>
        </div>
        <!--Content-->
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->

    <hr />

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 text-center">
        <h4 class="my-4 h4">Additional information</h4>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus
          suscipit modi sapiente illo soluta odit voluptates, quibusdam officia.
          Neque quibusdam quas a quis porro? Molestias illo neque eum in
          laborum.
        </p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
</main>

{% endblock content %}